#!/usr/bin/env php
<?php

use rdx\localoader\Application;
use rdx\localoader\Localoader;

require __DIR__ . '/vendor/autoload.php';

$app = new Application(new Localoader(getcwd()));
var_dump($app->run());
